### ISSUE TITLE
Screenshots are not avaiable

### ISSUE THREAD

**Issue by vahidvdn** [triniwiz/nativescript-image-zoom#1]
When I open this repo, screenshots is not loading. If I open the [pictures ](https://camo.githubusercontent.com/b328118dae9e2422b7b2637518390c1f6d9b78c0/68747470733a2f2f692e696d6775722e636f6d2f554c32306e70712e676966)in new page, I get the following error:
```
Content length exceeded
```

Would you please share them here?

**Comment by triniwiz** [comment]
Seems like GitHub has some problems with that external source

**Comment by triniwiz** [comment]
It's showing now

**Comment by vahidvdn** [comment]
How does it act? Is it pinch to zoom like instagram?

**Comment by triniwiz** [comment]
Yes it
