### ISSUE TITLE
Dynamic Src Binding via Javascript

### ISSUE THREAD

**Issue by throwingdarts** [triniwiz/nativescript-image-zoom#11]
I am trying to use this plugin with bound variables in the source but am having trouble getting the image to load/display.

`<ui:ImageZoom src="{{ 'http://www.my-content-url.com/' + dynamicDir + '/' + dynamicFilename }}" maxZoom="5" minZoom="2"/>`

Manually adding the values being passed works. Also it's good to note that my code is initially passing blank default values and then trying to change the values once the data is available and loaded. Is this not possible with this plugin? Updating the src dynamically?

I thought maybe I could try to build the ImageZoom in javascript and add it to the parent view once the src URI is available but there isn't documentation on how I might go about that?

Any help here is much appreciated.

**Comment by triniwiz** [comment]
Which platform ?

**Comment by throwingdarts** [comment]
I am using nativescript core. (Javascript)

**Comment by triniwiz** [comment]
The latest version should we working fine

**Comment by throwingdarts** [comment]
Any chance there is a code example available so I can see what I'm missing then? Thanks.

**Comment by triniwiz** [comment]
I’ve updated the demo you can check that out

**Comment by throwingdarts** [comment]
Thanks, this helped me determine I wasn't missing something except the width and height settings were not set. Image was loading, just not showing.
