### ISSUE TITLE
Image-zoom

### ISSUE THREAD

**Issue by Jogendra1234** [triniwiz/nativescript-image-zoom#34]
I have install the image-zoom plugin and then try to show image there so I'm getting the below error -
> Module 'nativescript-image-zoom' not found for element 'nativescript-image-zoom:ImageZoom'.
System.err:    > Class constructor View cannot be invoked without 'new'

**Comment by triniwiz** [comment]
That's v7 you need to install `@triniwiz/nativescrip-image-zoom`

**Comment by Whip** [comment]
That wasted so much time. Please update docs
