### ISSUE TITLE
Working with Angular and TypeScript? 

### ISSUE THREAD

**Issue by Archi20** [triniwiz/nativescript-image-zoom#4]
Hi,
Is it working with Angular? Try use in NS project but image not showing on page.

**Comment by Archi20** [comment]
Find way to to use this plugin in Angular. Maybe someone will be searching for this.

In main.ts file add:
`
import { registerElement } from "nativescript-angular/element-registry";
registerElement('ImageZoom', () => require('nativescript-image-zoom').ImageZoom);
`
It let You use `ImageZoom`  as template, and in your html file use it like:
`
<GridLayout class="main">
      <ImageZoom [src] = "mapPath" stretch="none" ></ImageZoom>
</GridLayout>
`
In component `mapPath` is path to your image.

**Comment by triniwiz** [comment]
Yes it works fine with angular
