### ISSUE TITLE
SubsamplingScaleImageView is not a constructor

### ISSUE THREAD

**Issue by HintOfLemon** [triniwiz/nativescript-image-zoom#7]
### If the demo apps cannot help and there is no issue for your problem, tell us about it

I run 'tns plugin add nativescript-image-zoom' and everything installs fine.
The error occurs when I load a page with the <ui:ImageZoom/> control present.
I do include the xlmns on the page element, but the application crashes with this error:
'TypeError: com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView is not a constructor
 File: image-zoom.js, line: 13, column: 15'

### Which platform(s) does your issue occur on?

-Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): Android -> 4.0.1
- Plugin(s): 
"dependencies": {
		"font-awesome": "^4.7.0",
		"nativescript-accordion": "^5.0.3",
		"nativescript-image-zoom": "^1.1.1",
		"nativescript-localstorage": "^1.1.5",
		"nativescript-theme-core": "~1.0.4",
		"nativescript-ui-sidedrawer": "^4.0.0",
		"tns-core-modules": "^4.0.0"
	},
"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.7.1",
		"typescript": "^2.8.3"
	}

### Please, tell us how to recreate the issue in as much detail as possible. 

I just installed it, and used it in xml as specified, with: src="~/res/img1.jpg" and no other attributes.

### Is there any code involved? 

<Page navigatedTo="onNavigated" xmlns:ui="nativescript-image-zoom" actionBarHidden="false" loaded="onLoaded" navigatingFrom="navigatingFrom">

    <ActionBar title="Test">
        <GridLayout class="action-bar" columns="*, 7*">
            <Label col="0" class="fa" text="&#xf053;" tap="goBack"></Label>
        </GridLayout>
    </ActionBar>

    <StackLayout>
        <ui:ImageZoom src="~/res/img1.jpg"/>
    </StackLayout>
</Page>

**Comment by triniwiz** [comment]
Thee plugin needs to be updated to support 4.x

**Comment by triniwiz** [comment]
Update to the latest version
